### PR TITLE
Fix unlimited undos

### LINKED ISSUE #9: Clicking undo after resetgame takes the user back
Maybe this is fine, if the user want's to undo "reset game"?

### PR DESCRIPTION
**Pull request by roessum**
Resolves #9 
Resolves #10

### CODE REVIEW

**Comment by nimrossum** [comment]
Can you explain why this fixes the issue?

File: src/App.tsx [hunk 1]
```diff
@@ -70,12 +70,16 @@ export default function App() {
...
     }))
     setUndosLeft(INITIAL_UNDOSLEFT)
+    setPrevState(getInitialState)
   }
 
   const undo = () => {
-    setState(prevState)
-    setQueue(state.userPieces)
-    setUndosLeft(undosLeft - 1)
+    // console.log(Object.is(prevState, state)) // This gives false..
```
Comment (nimrossum) [inline src/App.tsx:77]: Remove console.log
